#%RAML 1.0 Library
usage:
types:
  request-doc-type:
    type: object
    properties:
      bucketName:
        type: string
        required: true
        minLength: 1
        maxLength: 20
      folderPath:
        type: string
        required: true
        minLength: 1
        maxLength: 20
      fileName:
        type: string
        required: true
        minLength: 1
        maxLength: 20
      document:
        type: string
        required: true
        minLength: 10